package com.chatmvp.common.GreenDAOBean;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CHAT_BEAN".
*/
public class ChatBeanDao extends AbstractDao<ChatBean, Long> {

    public static final String TABLENAME = "CHAT_BEAN";

    /**
     * Properties of entity ChatBean.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, String.class, "UserId", false, "USER_ID");
        public final static Property UserHeadIcon = new Property(2, String.class, "UserHeadIcon", false, "USER_HEAD_ICON");
        public final static Property UserName = new Property(3, String.class, "UserName", false, "USER_NAME");
        public final static Property UserContent = new Property(4, String.class, "UserContent", false, "USER_CONTENT");
        public final static Property Time = new Property(5, String.class, "time", false, "TIME");
        public final static Property Type = new Property(6, int.class, "type", false, "TYPE");
        public final static Property Messagetype = new Property(7, int.class, "messagetype", false, "MESSAGETYPE");
        public final static Property UserVoiceTime = new Property(8, float.class, "UserVoiceTime", false, "USER_VOICE_TIME");
        public final static Property UserVoicePath = new Property(9, String.class, "UserVoicePath", false, "USER_VOICE_PATH");
        public final static Property UserVoiceUrl = new Property(10, String.class, "UserVoiceUrl", false, "USER_VOICE_URL");
        public final static Property SendState = new Property(11, int.class, "sendState", false, "SEND_STATE");
        public final static Property ImageUrl = new Property(12, String.class, "imageUrl", false, "IMAGE_URL");
        public final static Property ImageIconUrl = new Property(13, String.class, "imageIconUrl", false, "IMAGE_ICON_URL");
        public final static Property ImageLocal = new Property(14, String.class, "imageLocal", false, "IMAGE_LOCAL");
        public final static Property IsNew = new Property(15, int.class, "isNew", false, "IS_NEW");
        public final static Property IsComMeg = new Property(16, boolean.class, "isComMeg", false, "IS_COM_MEG");
    }


    public ChatBeanDao(DaoConfig config) {
        super(config);
    }
    
    public ChatBeanDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CHAT_BEAN\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"USER_ID\" TEXT," + // 1: UserId
                "\"USER_HEAD_ICON\" TEXT," + // 2: UserHeadIcon
                "\"USER_NAME\" TEXT," + // 3: UserName
                "\"USER_CONTENT\" TEXT," + // 4: UserContent
                "\"TIME\" TEXT," + // 5: time
                "\"TYPE\" INTEGER NOT NULL ," + // 6: type
                "\"MESSAGETYPE\" INTEGER NOT NULL ," + // 7: messagetype
                "\"USER_VOICE_TIME\" REAL NOT NULL ," + // 8: UserVoiceTime
                "\"USER_VOICE_PATH\" TEXT," + // 9: UserVoicePath
                "\"USER_VOICE_URL\" TEXT," + // 10: UserVoiceUrl
                "\"SEND_STATE\" INTEGER NOT NULL ," + // 11: sendState
                "\"IMAGE_URL\" TEXT," + // 12: imageUrl
                "\"IMAGE_ICON_URL\" TEXT," + // 13: imageIconUrl
                "\"IMAGE_LOCAL\" TEXT," + // 14: imageLocal
                "\"IS_NEW\" INTEGER NOT NULL ," + // 15: isNew
                "\"IS_COM_MEG\" INTEGER NOT NULL );"); // 16: isComMeg
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CHAT_BEAN\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, ChatBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String UserId = entity.getUserId();
        if (UserId != null) {
            stmt.bindString(2, UserId);
        }
 
        String UserHeadIcon = entity.getUserHeadIcon();
        if (UserHeadIcon != null) {
            stmt.bindString(3, UserHeadIcon);
        }
 
        String UserName = entity.getUserName();
        if (UserName != null) {
            stmt.bindString(4, UserName);
        }
 
        String UserContent = entity.getUserContent();
        if (UserContent != null) {
            stmt.bindString(5, UserContent);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(6, time);
        }
        stmt.bindLong(7, entity.getType());
        stmt.bindLong(8, entity.getMessagetype());
        stmt.bindDouble(9, entity.getUserVoiceTime());
 
        String UserVoicePath = entity.getUserVoicePath();
        if (UserVoicePath != null) {
            stmt.bindString(10, UserVoicePath);
        }
 
        String UserVoiceUrl = entity.getUserVoiceUrl();
        if (UserVoiceUrl != null) {
            stmt.bindString(11, UserVoiceUrl);
        }
        stmt.bindLong(12, entity.getSendState());
 
        String imageUrl = entity.getImageUrl();
        if (imageUrl != null) {
            stmt.bindString(13, imageUrl);
        }
 
        String imageIconUrl = entity.getImageIconUrl();
        if (imageIconUrl != null) {
            stmt.bindString(14, imageIconUrl);
        }
 
        String imageLocal = entity.getImageLocal();
        if (imageLocal != null) {
            stmt.bindString(15, imageLocal);
        }
        stmt.bindLong(16, entity.getIsNew());
        stmt.bindLong(17, entity.getIsComMeg() ? 1L: 0L);
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, ChatBean entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String UserId = entity.getUserId();
        if (UserId != null) {
            stmt.bindString(2, UserId);
        }
 
        String UserHeadIcon = entity.getUserHeadIcon();
        if (UserHeadIcon != null) {
            stmt.bindString(3, UserHeadIcon);
        }
 
        String UserName = entity.getUserName();
        if (UserName != null) {
            stmt.bindString(4, UserName);
        }
 
        String UserContent = entity.getUserContent();
        if (UserContent != null) {
            stmt.bindString(5, UserContent);
        }
 
        String time = entity.getTime();
        if (time != null) {
            stmt.bindString(6, time);
        }
        stmt.bindLong(7, entity.getType());
        stmt.bindLong(8, entity.getMessagetype());
        stmt.bindDouble(9, entity.getUserVoiceTime());
 
        String UserVoicePath = entity.getUserVoicePath();
        if (UserVoicePath != null) {
            stmt.bindString(10, UserVoicePath);
        }
 
        String UserVoiceUrl = entity.getUserVoiceUrl();
        if (UserVoiceUrl != null) {
            stmt.bindString(11, UserVoiceUrl);
        }
        stmt.bindLong(12, entity.getSendState());
 
        String imageUrl = entity.getImageUrl();
        if (imageUrl != null) {
            stmt.bindString(13, imageUrl);
        }
 
        String imageIconUrl = entity.getImageIconUrl();
        if (imageIconUrl != null) {
            stmt.bindString(14, imageIconUrl);
        }
 
        String imageLocal = entity.getImageLocal();
        if (imageLocal != null) {
            stmt.bindString(15, imageLocal);
        }
        stmt.bindLong(16, entity.getIsNew());
        stmt.bindLong(17, entity.getIsComMeg() ? 1L: 0L);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public ChatBean readEntity(Cursor cursor, int offset) {
        ChatBean entity = new ChatBean( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // UserId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // UserHeadIcon
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // UserName
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // UserContent
            cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5), // time
            cursor.getInt(offset + 6), // type
            cursor.getInt(offset + 7), // messagetype
            cursor.getFloat(offset + 8), // UserVoiceTime
            cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9), // UserVoicePath
            cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10), // UserVoiceUrl
            cursor.getInt(offset + 11), // sendState
            cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12), // imageUrl
            cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13), // imageIconUrl
            cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14), // imageLocal
            cursor.getInt(offset + 15), // isNew
            cursor.getShort(offset + 16) != 0 // isComMeg
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, ChatBean entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setUserHeadIcon(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setUserName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setUserContent(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setTime(cursor.isNull(offset + 5) ? null : cursor.getString(offset + 5));
        entity.setType(cursor.getInt(offset + 6));
        entity.setMessagetype(cursor.getInt(offset + 7));
        entity.setUserVoiceTime(cursor.getFloat(offset + 8));
        entity.setUserVoicePath(cursor.isNull(offset + 9) ? null : cursor.getString(offset + 9));
        entity.setUserVoiceUrl(cursor.isNull(offset + 10) ? null : cursor.getString(offset + 10));
        entity.setSendState(cursor.getInt(offset + 11));
        entity.setImageUrl(cursor.isNull(offset + 12) ? null : cursor.getString(offset + 12));
        entity.setImageIconUrl(cursor.isNull(offset + 13) ? null : cursor.getString(offset + 13));
        entity.setImageLocal(cursor.isNull(offset + 14) ? null : cursor.getString(offset + 14));
        entity.setIsNew(cursor.getInt(offset + 15));
        entity.setIsComMeg(cursor.getShort(offset + 16) != 0);
     }
    
    @Override
    protected final Long updateKeyAfterInsert(ChatBean entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(ChatBean entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(ChatBean entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
