package com.chatmvp.common.GreenDAOBean;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.chatmvp.common.GreenDAOBean.ChatBean;
import com.chatmvp.common.GreenDAOBean.RecentItem;

import com.chatmvp.common.GreenDAOBean.ChatBeanDao;
import com.chatmvp.common.GreenDAOBean.RecentItemDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig chatBeanDaoConfig;
    private final DaoConfig recentItemDaoConfig;

    private final ChatBeanDao chatBeanDao;
    private final RecentItemDao recentItemDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        chatBeanDaoConfig = daoConfigMap.get(ChatBeanDao.class).clone();
        chatBeanDaoConfig.initIdentityScope(type);

        recentItemDaoConfig = daoConfigMap.get(RecentItemDao.class).clone();
        recentItemDaoConfig.initIdentityScope(type);

        chatBeanDao = new ChatBeanDao(chatBeanDaoConfig, this);
        recentItemDao = new RecentItemDao(recentItemDaoConfig, this);

        registerDao(ChatBean.class, chatBeanDao);
        registerDao(RecentItem.class, recentItemDao);
    }
    
    public void clear() {
        chatBeanDaoConfig.clearIdentityScope();
        recentItemDaoConfig.clearIdentityScope();
    }

    public ChatBeanDao getChatBeanDao() {
        return chatBeanDao;
    }

    public RecentItemDao getRecentItemDao() {
        return recentItemDao;
    }

}
