package com.chatmvp.common.GreenDAOBean;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "RECENT_ITEM".
*/
public class RecentItemDao extends AbstractDao<RecentItem, Long> {

    public static final String TABLENAME = "RECENT_ITEM";

    /**
     * Properties of entity RecentItem.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property UserId = new Property(1, String.class, "userId", false, "USER_ID");
        public final static Property HeadImg = new Property(2, int.class, "headImg", false, "HEAD_IMG");
        public final static Property Name = new Property(3, String.class, "name", false, "NAME");
        public final static Property Message = new Property(4, String.class, "message", false, "MESSAGE");
        public final static Property NewNum = new Property(5, int.class, "newNum", false, "NEW_NUM");
        public final static Property Time = new Property(6, long.class, "time", false, "TIME");
        public final static Property MsgType = new Property(7, int.class, "msgType", false, "MSG_TYPE");
        public final static Property VoiceTime = new Property(8, int.class, "voiceTime", false, "VOICE_TIME");
    }


    public RecentItemDao(DaoConfig config) {
        super(config);
    }
    
    public RecentItemDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"RECENT_ITEM\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"USER_ID\" TEXT," + // 1: userId
                "\"HEAD_IMG\" INTEGER NOT NULL ," + // 2: headImg
                "\"NAME\" TEXT," + // 3: name
                "\"MESSAGE\" TEXT," + // 4: message
                "\"NEW_NUM\" INTEGER NOT NULL ," + // 5: newNum
                "\"TIME\" INTEGER NOT NULL ," + // 6: time
                "\"MSG_TYPE\" INTEGER NOT NULL ," + // 7: msgType
                "\"VOICE_TIME\" INTEGER NOT NULL );"); // 8: voiceTime
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"RECENT_ITEM\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, RecentItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(2, userId);
        }
        stmt.bindLong(3, entity.getHeadImg());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
 
        String message = entity.getMessage();
        if (message != null) {
            stmt.bindString(5, message);
        }
        stmt.bindLong(6, entity.getNewNum());
        stmt.bindLong(7, entity.getTime());
        stmt.bindLong(8, entity.getMsgType());
        stmt.bindLong(9, entity.getVoiceTime());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, RecentItem entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String userId = entity.getUserId();
        if (userId != null) {
            stmt.bindString(2, userId);
        }
        stmt.bindLong(3, entity.getHeadImg());
 
        String name = entity.getName();
        if (name != null) {
            stmt.bindString(4, name);
        }
 
        String message = entity.getMessage();
        if (message != null) {
            stmt.bindString(5, message);
        }
        stmt.bindLong(6, entity.getNewNum());
        stmt.bindLong(7, entity.getTime());
        stmt.bindLong(8, entity.getMsgType());
        stmt.bindLong(9, entity.getVoiceTime());
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public RecentItem readEntity(Cursor cursor, int offset) {
        RecentItem entity = new RecentItem( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // userId
            cursor.getInt(offset + 2), // headImg
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // name
            cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4), // message
            cursor.getInt(offset + 5), // newNum
            cursor.getLong(offset + 6), // time
            cursor.getInt(offset + 7), // msgType
            cursor.getInt(offset + 8) // voiceTime
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, RecentItem entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setUserId(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setHeadImg(cursor.getInt(offset + 2));
        entity.setName(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setMessage(cursor.isNull(offset + 4) ? null : cursor.getString(offset + 4));
        entity.setNewNum(cursor.getInt(offset + 5));
        entity.setTime(cursor.getLong(offset + 6));
        entity.setMsgType(cursor.getInt(offset + 7));
        entity.setVoiceTime(cursor.getInt(offset + 8));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(RecentItem entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(RecentItem entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(RecentItem entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
